### ISSUE TITLE
Breaks typo3 8.7.25 on symlinked webroot

### ISSUE THREAD

**Issue by abvdveen** [TYPO3/phar-stream-wrapper#47] opened 2019-05-15 10:52 UTC
On a typo3 8.7.25 installation that has a symlinked webroot, the following errors occur:

Warning: Uncaught TYPO3\PharStreamWrapper\Exception: Executing phar:///data/sites/web/depontnl/www/typo3conf/ext/emogrifier/Resources/Private/Php/Emogrifier.phar/vendor/autoload.php is denied in /data/sites/web/depontnl/subsites/typo3_src-8.7.25/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php:39 Stack trace: #0 /data/sites/web/depontnl/subsites/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/Behavior.php(72): TYPO3\CMS\Core\IO\PharStreamWrapperInterceptor->assert('phar:///data/si...', 'stream_open') #1 /data/sites/web/depontnl/subsites/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/Manager.php(110): TYPO3\PharStreamWrapper\Behavior->assert('phar:///data/si...', 'stream_open') #2 /data/sites/web/depontnl/subsites/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(421): TYPO3\PharStreamWrapper\Manager->assert('phar:///data/si...', 'stream_open') #3 /data/sites/web/depontnl/subsites/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(256): TYPO3\ in /data/sites/web/depontnl/subsites/typo3_src-8.7.25/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php on line 39

Fatal error: TYPO3\CMS\Core\Utility\GeneralUtility::requireOnce(): Failed opening required 'phar:///data/sites/web/depontnl/www/typo3conf/ext/emogrifier/Resources/Private/Php/Emogrifier.phar/vendor/autoload.php' (include_path='.') in /data/sites/web/depontnl/subsites/typo3_src-8.7.25/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4249

Reverting to 8.7.24 resolves it.
The same setup, but then a non-symlinked webroot on staging, generates no errors on 8.7.25, so it seems related to the symlink.

**Comment by ohader** [comment] 2019-05-15 11:21
Thanks for your report. In a TYPO3 CMS context, that should be solved with https://review.typo3.org/c/Packages/TYPO3.CMS/+/60756 which is target to be released in TYPO3 v8.7.26

**Comment by ohader** [comment] 2019-05-15 11:25
https://review.typo3.org/c/Packages/TYPO3.CMS/+/60762

TYPO3 v8.7.26 should be available on via composer in a couple of minutes and some additional minutes later via get.typo3.org as well

**Comment by ohader** [comment] 2019-05-15 11:25
@abvdveen Please report back to this issue whether the problem is solved with new TYPO3 release. Thx

**Comment by ohader** [comment] 2019-05-15 12:58
https://get.typo3.org/release-notes/8.7.26

**Comment by abvdveen** [comment] 2019-06-12 15:52
This indeed fixes the issue, thanks!

**Closed** 2019-06-12 18:45 UTC
