### ISSUE TITLE
Breaking included AWS Phar 

### ISSUE THREAD

**Issue by neoacevedo** [TYPO3/phar-stream-wrapper#21] opened 2019-03-16 22:23 UTC
Hi. Joomla 3.9.4 updated/included this package. 
Currently I'm using aws.phar to use for S3, but since last update, I'm getting this error:

>  Uncaught TYPO3\PharStreamWrapper\Exception: Unexpected file extension in "phar://aws-3.67.5.phar/aws-autoloader.php"

This error is related to this package, not in Joomla or my own code. Maybe a bug?

**Comment by ohader** [comment] 2019-03-16 22:34
Can you please point to the specific version of the aws.phar file, how it is used/included and mention the exact PHP version (and OS distribution) you're using? Thx

**Comment by neoacevedo** [comment] 2019-03-16 22:41
Hi.
It happens in any Linux version with PHP >= 7.1
I'm using the latest AWS phar file (3.90.3) and requiring it according with the AWS documentation: `require '/path/to/aws.phar';`

**Comment by ohader** [comment] 2019-03-17 17:16
## Current workaround

instead of 

```php
require('phar:///path/to/aws.phar');
```

use
```php
require('phar:///path/to/aws.phar/aws-autoloader.php');
```

This is was the stub of `aws.phar` is doing anyway internally.

## Explanation

The stub of libraries like `geoip2` (build with `php-box`) looks like the following. When invoking the `phar://` stream, the full path is still given internally by using `__FILE__`. That way, the file path can be mapped to its internal alias name.

```
Phar::mapPhar('geoip2.phar');
require 'phar://' . __FILE__ . '/phar-stub.php';
```

The stub of the `aws` library looks like the following and does not contain any internal reference to it's original file. That's the reason why the internal alias `aws-3.90.3.phar` cannot be checked and results in an empty base-name. The work-around above uses the `phar://` stream and thus triggers alias resolving.

```
Phar::mapPhar('aws-3.90.3.phar');
require 'phar://aws-3.90.3.phar/aws-autoloader.php';
```

**Comment by ohader** [comment] 2019-03-17 17:29
In PR #22 I've added test cases first in order to reproduce the behavior. Next step would be a fix...

**Comment by neoacevedo** [comment] 2019-03-19 19:26
I needed only `require 'phar://aws-3.90.3.phar/aws-autoloader.php';` and it worked again.

**Comment by jurihahn** [comment] 2019-04-09 21:08
@ohader this solution does not work with "geoip2.phar"?

**Comment by jurihahn** [comment] 2019-04-11 20:23
i have workaround for "GeoIP2.phar"
`require_once ( 'phar://' . __DIR__ . '/geoip2.phar/vendor/autoload.php' );`

**Comment by ohader** [comment] 2019-04-28 09:35
Please test the references pull-requests #31 (PHP7) or #32 (PHP5) and check whether the originally reported bug of this ticket is solved. Thanks!

**Closed** 2019-05-05 17:30 UTC
Labels: bug
